### ISSUE TITLE
connect() got an unexpected keyword argument 'use_ssl'

### ISSUE THREAD

**Issue by tdubbz** [jterrace/pyharmony#1]
Having issues getting past this error... to install the libraries I just used 
   # sudo apt-get install python-argh
   # sudo apt-get install python-sleekxmpp
   # sudo apt-get install python-requests

Linux  3.8.0-19-generic #30-Ubuntu
# PYTHONPATH="." python harmony --email XXXXX --password XXXXX --harmony_ip 192.168.0.236 show_config

INFO    urllib3.connectionpool  Starting new HTTPS connection (1): svcs.myharmony.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/pyharmony/harmony/__main__.py", line 83, in <module>
    main()
  File "/tmp/pyharmony/harmony/**main**.py", line 79, in main
    sys.exit(args.func(args))
  File "/tmp/pyharmony/harmony/**main**.py", line 37, in show_config
    token = login_to_logitech(args)
  File "/tmp/pyharmony/harmony/**main**.py", line 28, in login_to_logitech
    args.harmony_ip, args.harmony_port, token)
  File "/tmp/pyharmony/harmony/auth.py", line 111, in swap_auth_token
    use_tls=False, use_ssl=False)
TypeError: connect() got an unexpected keyword argument 'use_ssl'

**Comment by jpoppe** [comment]
I had the same issue but solved it by installing a more recent version of the sleekxmpp library.

For Debian/Ubuntu run:
sudo apt-get purge python-sleekxmpp
sudo pip install sleekxmpp

Or:
sudo pip install --upgrade sleekxmpp

**Comment by wayner9** [comment]
Shouldn't the line # sudo apt-get install python-argh (from above)

actually be:

# sudo apt-get install python-argparse

**Comment by Folcr** [comment]
@jpoppe is right. His recommendation to install the latest sleekxmpp has solved the issue with the error "use_ssl" at my Ubuntu 14.04.
THanks.
