### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by astanid** [jterrace/pyharmony#10]

**Comment by astanid** [comment]
looks like it requires Visual studio. I installed 2013 version - still the same error :(

**Comment by astanid** [comment]
...

**Comment by tatoosh** [comment]
It is not working for me:
> git clone https://github.com/jterrace/pyharmony.git
>python harmony
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/pyharmony/harmony/__main__.py", line 10, in <module>
    from harmony import auth
ImportError: No module named harmony
```
