### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by robertgoolsby** [jterrace/pyharmony#6]
Any thoughts on this?  I 

Command:

PYTHONPATH="." python harmony --email <email> --password <opassword> --harmony_ip 192.168.1.23 show_config

output:

INFO    requests.packages.urllib3.connectionpool        Starting new HTTPS connection (1): svcs.myharmony.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/pyharmony-master/harmony/__main__.py", line 83, in <module>
    main()
  File "/home/pi/pyharmony-master/harmony/**main**.py", line 79, in main
    sys.exit(args.func(args))
  File "/home/pi/pyharmony-master/harmony/**main**.py", line 37, in show_config
    token = login_to_logitech(args)
  File "/home/pi/pyharmony-master/harmony/**main**.py", line 23, in login_to_logitech
    token = auth.login(args.email, args.password)
  File "/home/pi/pyharmony-master/harmony/auth.py", line 41, in login
    result = resp.json().get('GetUserAuthTokenResult', None)
TypeError: 'dict' object is not callable

**Comment by LaurentTrk** [comment]
Hello,
You need to upgrade your requests package: 
`pip install --upgrade requests`
Hope it helps...
