### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by wayner9** [jterrace/pyharmony#8]
Sorry, but I need some help as I don't know how to use python modules.

What do I need to do to run this in Python for Windows?  I have downloaded the files and have them in a folder called harmony.  Do I have to do something to install the module to get it to run from a command line?  And why do the examples include a PTHONPATH?

From the command line I type c:\python27\python\harmony and I get 
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\pyharmony-master\harmony__main__.py", line 10, in <module>
    from harmony import auth
ImportError: No module named harmony

**Comment by wayner9** [comment]
I am still really confused here.  I am learning more about modules but when I try to install pyharmony using pip I get an error since it can't find a setup.py file.  Shouldn't there be such a file for pyharmony?

The command I am trying is:  sudo pip install git+git://github.com/jterrace/pyharmony
